### PR TITLE
load-reg019-001.sh: Update script due to installing ofed 4.4

### PR DESCRIPTION
**Pull request by ZiyadAtiyyeh**
We will check ofed 4.4 instead of ofed 4.2.

Signed-off-by: Ziyad Atiyyeh <ziyadat@mellanox.com>

### CODE REVIEW

**Comment by ZiyadAtiyyeh** [comment]
Hi, Please check attached console output that show you the devlink and kernel version.
commandsoutput

**Comment by roidayan** [comment]
It's because the .config used for this custom kernel rpm set devlink as built-in. The kernel repo doesn't contain a .config. when you build a kernel you supply a .config or create new one with default values. The default is a module. All distros leave it as a module.

**Comment by ZiyadAtiyyeh** [comment]
I did not close this pull request explicitly, i closed due to reaming the branch to more meaningful name and creating new pull request.

**Comment by ZiyadAtiyyeh** [comment]
Now, I said  "check ofed 4.4" because this is the reason of changing the load-reg019-001.sh but I should connect it to this file only.

Lets ignore this pull request and switch to the new one.

**Pull request closed without merging**
